apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hlds
  namespace: hlds
spec:
  selector:
    matchLabels:
      app: hlds
  replicas: 1
  template:
    metadata:
      labels:
        app: hlds
    spec:
      containers:
      - name: hlds
        image: hitman99/hlds:0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27020
        - containerPort: 27015
        - containerPort: 26900
        resources:
          limits:
            memory: "400Mi"
        env:
        - name: START_MAP
          value: bounce
        - name: ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: hlds
              key: ADMIN_NAME
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: hlds
              key: ADMIN_PASS
        - name: SERVER_NAME
          value: "HLDS on K8S "
        - name: GAME
          value: "valve"
        - name: MAXPLAYERS
          value: "10"
        - name: INSECURE
          value: " "
